### ISSUE TITLE
ANRs being reported on Android

### ISSUE THREAD

**Issue by andrewescutia** [launchdarkly/flutter-client-sdk#15]
**Describe the bug**
It appears that we are receiving ANRs on Launch Darkly client calls. It is currently our top reported ANR. Specifically in regards to the LDClient.identify() call. Before migrating over to the Flutter library we were making use of the Xamarin library and would experience similar. In debugging the issue locally it appears the bug might be within the native LaunchDarkly Android library that both the Flutter and Xamarin SDKs reference. 

I believe the issue may be around how FutureTasks are used within the Library, specifically the .get() calls on them which will block current (UI) thread.

ex: `LDClient.get().identify(ldUser).get()`

This is found on line 260 in `LaunchdarklyFlutterClientSdkPlugin.kt` and is the line being reported in the Android and Crashlytics reports further below.

**To reproduce**
Have not found a way yet to reproduce

**Expected behavior**
For the SDK to not block the UI thread

**Logs**

Crashlytics Log:
> main (waiting): tid=1 systid=10065 
       at java.lang.Object.wait(Native method)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at com.launchdarkly.sdk.android.LDAwaitFuture.get(LDFutures.java:128)
       at com.launchdarkly.launchdarkly_flutter_client_sdk.LaunchdarklyFlutterClientSdkPlugin.onMethodCall(LaunchdarklyFlutterClientSdkPlugin.kt:260)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
       at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(lambda)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

Google Play Log:

> Type
"main" prio=5 tid=1 Waiting
  at java.lang.Object.wait (Native method)
  at java.lang.Object.wait (Object.java:442)
  at java.lang.Object.wait (Object.java:568)
  at com.launchdarkly.sdk.android.LDAwaitFuture.get (LDFutures.java:128)
  at com.launchdarkly.launchdarkly_flutter_client_sdk.LaunchdarklyFlutterClientSdkPlugin.onMethodCall (LaunchdarklyFlutterClientSdkPlugin.kt:260)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java:262)
  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler (DartMessenger.java:296)
  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger (DartMessenger.java:320)
  at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run (lambda)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:223)
  at android.app.ActivityThread.main (ActivityThread.java:7723)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:612)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:997)

**SDK version**
launchdarkly_flutter_client_sdk: 1.0.0

**Language version, developer tools**
[✓] Flutter (Channel stable, 2.10.5, on macOS 11.6.6 20G624 darwin-x64, locale en-US)

**Additional context**

**Comment by kinyoklion** [comment]
Hello @andrewescutia,

Thank you for the report and the detailed logs! I've filed an internal issue and we will look into it.

_Filed internally as 155757_

Thank you,
Ryan

**Comment by kinyoklion** [comment]
Hello @andrewescutia,

This should be fixed in release `1.1.2`. 

The identify call will now execute on an IO thread.

Thank you!
- Ryan

**Comment by fparhat-rbi** [comment]
Hi @kinyoklion we are seeing similar ANR's (similar stack trace) in our crashlytics for our **react native** application.
Is there a similar fix/update for the **react-native-client-sdk**?

**Comment by fparhat-rbi** [comment]
Hi @kinyoklion I submitted an issue
https://github.com/launchdarkly/react-native-client-sdk/issues/144
