### ISSUE TITLE
RuntimeException on Android

### ISSUE THREAD

**Issue by aralghamdi** [launchdarkly/flutter-client-sdk#21]
**Describe the bug**
We get `RuntimeException` reports on Sentry. this exception happens once in a while to our users. However, we couldn't reproduce it.

**Sentry Logs**
```
android.os.DeadSystemException: null
    at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:571)
    at android.app.PendingIntent.getBroadcast(PendingIntent.java:547)
    at com.launchdarkly.sdk.android.PollingUpdater.c(PollingUpdater.java:2)
    at com.launchdarkly.sdk.android.PollingUpdater.g(PollingUpdater.java:2)
    at e.g.c.f.t.H(ConnectivityManager.java:1)
    at e.g.c.f.t.m(ConnectivityManager.java:21)
    at e.g.c.f.t.u(ConnectivityManager.java:9)
    at e.g.c.f.m0.h0(LDClient.java:2)
    at e.g.c.f.m0.i0(LDClient.java:5)
    at com.launchdarkly.sdk.android.ConnectivityReceiver.onReceive(ConnectivityReceiver.java:6)
    at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52511(LoadedApk.java:1313)
    at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7
    at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6495)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

java.lang.RuntimeException: android.os.DeadSystemException
    at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:571)
    at android.app.PendingIntent.getBroadcast(PendingIntent.java:547)
    at com.launchdarkly.sdk.android.PollingUpdater.c(PollingUpdater.java:2)
    at com.launchdarkly.sdk.android.PollingUpdater.g(PollingUpdater.java:2)
    at e.g.c.f.t.H(ConnectivityManager.java:1)
    at e.g.c.f.t.m(ConnectivityManager.java:21)
    at e.g.c.f.t.u(ConnectivityManager.java:9)
    at e.g.c.f.m0.h0(LDClient.java:2)
    at e.g.c.f.m0.i0(LDClient.java:5)
    at com.launchdarkly.sdk.android.ConnectivityReceiver.onReceive(ConnectivityReceiver.java:6)
    at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52511(LoadedApk.java:1313)
    at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7
    at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6495)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in com.launchdarkly.sdk.android.ConnectivityReceiver@118e39d
    at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52511(LoadedApk.java:1323)
    at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7
    at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6495)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**SDK version**
`launchdarkly_flutter_client_sdk: ^1.1.3`

**Flutter doctor**
```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1889], locale en-US)
    • Flutter version 3.0.5 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
```

**OS/platform**
Android 8.1.0

**Comment by kinyoklion** [comment]
Hello @aralghamdi,

This looks like an android system crash, https://developer.android.com/reference/android/os/DeadSystemException, and the SDK has some outstanding work happening during the crash.

Likely any point where a thread is suspended and the system is waking it in the process of restarting. Typically these would be InterruptedExceptions, if the system was not crashing.

I will look through the stacks for anything that looks like it could be an issue, but this is like spurious in regards to the SDK itself.

Are the majority of these coming from a specific android device type or manufacturer,  user, etc? 

Thanks,
Ryan

**Comment by aralghamdi** [comment]
> Hello @aralghamdi,
> 
> This looks like an android system crash, https://developer.android.com/reference/android/os/DeadSystemException, and the SDK has some outstanding work happening during the crash.
> 
> Likely any point where a thread is suspended and the system is waking it in the process of restarting. Typically these would be InterruptedExceptions, if the system was not crashing.
> 
> I will look through the stacks for anything that looks like it could be an issue, but this is like spurious in regards to the SDK itself.
> 
> Are the majority of these coming from a specific android device type or manufacturer, user, etc?
> 
> Thanks, Ryan

@kinyoklion thank you for the fast response and clarification. 
Yes, all of our users are using the Sunmi D2 mini device. and every time they get this exception it has LD SDK in the stack trace.

**Comment by kinyoklion** [comment]
@aralghamdi Are these devices configured such that they have a watchdog timeout? Is it possible this would otherwise manifest as an ANR, but a watchdog is resetting the device instead?

We have been working on improving the lock management in the android SDK, so that may improve the situation.

**Comment by aralghamdi** [comment]
> @aralghamdi Are these devices configured such that they have a watchdog timeout? Is it possible this would otherwise manifest as an ANR, but a watchdog is resetting the device instead?
> 
> We have been working on improving the lock management in the android SDK, so that may improve the situation.

@kinyoklion we have confirmed that Sunmi devices have a watchdog configuration. I appreciate your support and please keep us updated on any updates that can fix this issue.

**Comment by kinyoklion** [comment]
@aralghamdi I have released version 1.1.4. This version contains an updated launchdarkly android SDK. The updated android SDK contains work we have been doing to fix android ANR issues. If the issue is being caused by a timeout because our SDK is triggering an ANR situation, then this should help to mitigate it.

**Comment by aralghamdi** [comment]
> @aralghamdi I have released version 1.1.4. This version contains an updated launchdarkly android SDK. The updated android SDK contains work we have been doing to fix android ANR issues. If the issue is being caused by a timeout because our SDK is triggering an ANR situation, then this should help to mitigate it.

@kinyoklion thank you for the update, we will include this version in our next release and let know if it fixed the issue.

**Comment by aralghamdi** [comment]
@kinyoklion v1.1.4 fixed the issue, thank you for your support
