### ISSUE TITLE
Android: `LDClient.get()` was called before `init()`

### ISSUE THREAD

**Issue by t-unit** [launchdarkly/flutter-client-sdk#37]
**Describe the bug**
After updating to version [2.0.0](https://pub.dev/packages/launchdarkly_flutter_client_sdk/versions/2.0.0), we noticed that on some devices our app does not start anymore.

**To reproduce**
Calling
```dart
    final config = LDConfigBuilder(mobileKey).build();
    final contextBuilder = LDContextBuilder()..kind('user', userId);
    await LDClient.startWithContext(config, contextBuilder.build());
```
triggers the issue:

```
2023-05-24 17:33:28.645 29512-29579 AndroidRuntime          pid-29512                            E  FATAL EXCEPTION: DefaultDispatcher-worker-2
	Process: com.circuskitchens.consumer.staging, PID: 29512
	com.launchdarkly.sdk.android.LaunchDarklyException: LDClient.get() was called before init()!
		at com.launchdarkly.sdk.android.LDClient.get(LDClient.java:279)
		at com.launchdarkly.launchdarkly_flutter_client_sdk.LaunchdarklyFlutterClientSdkPlugin$onMethodCall$1$1.invokeSuspend(LaunchdarklyFlutterClientSdkPlugin.kt:360)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
		at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
		at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
		at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
		Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b4438d9, Dispatchers.Default]
```

**Expected behavior**
Startup finishes without any exceptions

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
[2.0.0](https://pub.dev/packages/launchdarkly_flutter_client_sdk/versions/2.0.0)

**Language version, developer tools**
Flutter 3.7.11

**OS/platform**
Motorola one zoom
Android 10

**Additional context**
Note, we can only reproduce this on certain devices.

**Comment by tanderson-ld** [comment]
Thank you for submitting this @t-unit , we'll look into this and respond shortly.

**Comment by tanderson-ld** [comment]
Does this happen 100% of the time on the device that you have been able to reproduce it on?  This will help us determine if it is a race condition.  I'm looking at the threading around where that crash is happening and the changes we made for 2.0.0 in that area, and it doesn't point to anything obvious.

**Comment by tanderson-ld** [comment]
The best theory we have right now is the code is not blocking on a future where it probably should be.  During development, we concluded it wasn't necessary, but perhaps we are missing a threading case.  If you are willing to try a change in the library itself and see if that fixes things, here is a diff to try.

```kotlin
diff --git a/android/src/main/kotlin/com/launchdarkly/launchdarkly_flutter_client_sdk/LaunchdarklyFlutterClientSdkPlugin.kt b/android/src/main/kotlin/com/launchdarkly/launchdarkly_flutter_client_sdk/LaunchdarklyFlutterClientSdkPlugin.kt
index 5351d68..44defdf 100644
--- a/android/src/main/kotlin/com/launchdarkly/launchdarkly_flutter_client_sdk/LaunchdarklyFlutterClientSdkPlugin.kt
+++ b/android/src/main/kotlin/com/launchdarkly/launchdarkly_flutter_client_sdk/LaunchdarklyFlutterClientSdkPlugin.kt
@@ -357,10 +357,10 @@ public class LaunchdarklyFlutterClientSdkPlugin: FlutterPlugin, MethodCallHandle
             } catch (ignored: LaunchDarklyException) {
               // We have not already initialized the native SDK.
               completion = initClient()
-              LDClient.get().registerAllFlagsListener(allFlagsListener)
             }
             try {
               completion.get()
+              LDClient.get().registerAllFlagsListener(allFlagsListener)
             } finally {
               callFlutter("completeStart", null)
             }
```

**Comment by t-unit** [comment]
> Does this happen 100% of the time on the device that you have been able to reproduce it on? 

We maybe 20-30% crashes on startup with the device mentioned.

> Do you see this behavior on 1.x before the upgrade by chance? Perhaps it is coincidence that this was seen now.

No

> Do you ever call close() on the SDK?

No

> In changes for 2.0.0, we changed the plugin threading to run on Dispatcher.IO instead of the Dispatcher.Main. If this was related to the issue you're seeing, we'd expect this to be happening all the time and on more devices. Can you describe the threading you're calling start() or startWithContext() from?

We call it in the `main` function of Flutter before `runApp` is called. Basic sequence is:
```dart
void main() {
    [other startup operations]

    LDClient.startWithContext([...]);
    LDClient.startFuture();

    [other startup operations]

    runApp([...])
```

**Comment by t-unit** [comment]
I tried applying your patch, but we are still getting some issues:

```
2023-05-25 09:06:43.756 27330-27330 DartMessenger           com.circuskitchens.consumer.staging  E  Uncaught exception in binary message listener
com.launchdarkly.sdk.android.LaunchDarklyException: LDClient.get() was called before init()!
	at com.launchdarkly.sdk.android.LDClient.get(LDClient.java:279)
	at com.launchdarkly.launchdarkly_flutter_client_sdk.LaunchdarklyFlutterClientSdkPlugin.onMethodCall(LaunchdarklyFlutterClientSdkPlugin.kt:402)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
2023-05-25 09:06:43.803 27330-27392 AndroidRuntime          com.circuskitchens.consumer.staging  E  FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: com.circuskitchens.consumer.staging, PID: 27330
java.util.concurrent.ExecutionException: com.launchdarkly.sdk.android.LaunchDarklyException: Client initialization requires a valid evaluation context (context key must not be null or empty)
	at com.launchdarkly.sdk.android.LDFailedFuture.get(LDFutures.java:67)
	at com.launchdarkly.launchdarkly_flutter_client_sdk.LaunchdarklyFlutterClientSdkPlugin$onMethodCall$1$1.invokeSuspend(LaunchdarklyFlutterClientSdkPlugin.kt:362)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f023e99, Dispatchers.Default]
Caused by: com.launchdarkly.sdk.android.LaunchDarklyException: Client initialization requires a valid evaluation context (context key must not be null or empty)
	at com.launchdarkly.sdk.android.LDClient.init(LDClient.java:99)
	at com.launchdarkly.launchdarkly_flutter_client_sdk.LaunchdarklyFlutterClientSdkPlugin$onMethodCall$1$1$3.invoke(LaunchdarklyFlutterClientSdkPlugin.kt:348)
	at com.launchdarkly.launchdarkly_flutter_client_sdk.LaunchdarklyFlutterClientSdkPlugin$onMethodCall$1$1$3.invoke(LaunchdarklyFlutterClientSdkPlugin.kt:348)
	at com.launchdarkly.launchdarkly_flutter_client_sdk.LaunchdarklyFlutterClientSdkPlugin$onMethodCall$1$1.invokeSuspend(LaunchdarklyFlutterClientSdkPlugin.kt:359)
	... 8 more
```

**Comment by tanderson-ld** [comment]
Could you include a snippet of the code where you are constructing the context using the LDContextBuilder?

**Comment by t-unit** [comment]
> Could you include a snippet of the code where you are constructing the context using the LDContextBuilder?

Sure:
```dart

  Future<void> init({required String mobileKey, required String userId}) async {
    final config = LDConfigBuilder(mobileKey).build();
    final contextBuilder = LDContextBuilder()..kind('user', userId);
    await LDClient.startWithContext(config, contextBuilder.build());
  }
```

The `mobileKey` can never be empty. Our part of the code calling `init` makes sure of that. Only thing I found out that might happen is that `userId` is an empty string. Might that be a problem?

**Comment by tanderson-ld** [comment]
`userId` must be non-empty.  In 1.x, we were automatically generating user keys if it was empty.  In 2.x, we now require them to be non-empty if provided.  You also have the option to omit the context key at which point a key will be generated and the context will become anonymous.  [Here's the documentation on the `kind(...)` function that states it must be non-empty.](https://github.com/launchdarkly/flutter-client-sdk/blob/main/lib/ld_context.dart#L41)

To help clarify, the mobile key and context key are different.  The mobile key is used by the SDK to authenticate to our servers.  A context key is a unique identifier for a given context.  In your code, the `userId` is the context key for the `user` context.  In 2.x you can now have multiple contexts and each can have a unique identifier.  I included some links below with good examples.

Here are relevant docs that I recommend taking a glance over:

https://docs.launchdarkly.com/home/contexts
https://docs.launchdarkly.com/home/contexts/multi-contexts
https://docs.launchdarkly.com/home/contexts/context-kinds

**Comment by t-unit** [comment]
Thanks for the info and your help! 

It would be great to get some proper diagnostics (error message) when handing in an empty userId. We will do some test with updates to our code that make sure the user id can not be `null`. I'll let you know once we have some results

**Comment by t-unit** [comment]
@tanderson-ld we ran som tests are still getting this error sometimes. In case there is no real user id, we now supply `"?"` to your sdk. While using version 2.0.1, we still get the following stack trace:

```
com.launchdarkly.sdk.android.LaunchDarklyException: LDClient.get() was called before init()!
	at com.launchdarkly.sdk.android.LDClient.get(LDClient.java:279)
	at com.launchdarkly.launchdarkly_flutter_client_sdk.LaunchdarklyFlutterClientSdkPlugin$onMethodCall$1$1.invokeSuspend(LaunchdarklyFlutterClientSdkPlugin.kt:360)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c7e7570, Dispatchers.Default]
```

**Comment by tanderson-ld** [comment]
Thank you for following up.  We want to get it figured out for everyone.  @t-unit, a few questions about the emulator case.

1. Is it happening on the emulator on startup or in some other scenario like resuming the app?
2. How frequently is it happening on the emulator?  100%?  20-30% like the other device you had seen it on?

We'll take some more time looking at it today.

**Comment by tanderson-ld** [comment]
@vasilich6107, thank you for confirming you are also seeing the issue.  Can you provide the stack trace you are seeing when you run into this issue?  What device and frequency are you seeing it?

Thanks!

**Comment by t-unit** [comment]
> 1. Is it happening on the emulator on startup or in some other scenario like resuming the app?

It happens on startup of the app, haven't seen this issue when resuming.

> 2. How frequently is it happening on the emulator?  100%?  20-30% like the other device you had seen it on?

Happened during one out of two attempts on this particular emulator

**Comment by tanderson-ld** [comment]
@t-unit , after spending some time looking into this again, I have been able to reproduce the issue by slowing down portions of the code.  The root cause related to a threading change we made recently.  We will have a fix in the next few days (perhaps today if testing goes smoothly).

**Comment by tanderson-ld** [comment]
@t-unit , the 2.0.2 version is now available.  Please let me know if that fixes it for you!  Thanks again for helping track down the issue.

@vasilich6107 , could you also give 2.0.2 a try and see if you still see an issue?

**Comment by t-unit** [comment]
@tanderson-ld your fix just passed our QA. Looks like issue is resolved!
